
ROAD_PENALTY = -0.5
SAFE_ZONE_REWARD = 1.0
GAME_WON_REWARD = 10.0
ADVANCEMENT_REWARD = 1.5
GAME_OVER_PENALTY = -5.0
EXCEEDED_TIME_PENALTY = -1.0
STEP_PENALTY = -0.05
REGRESSION_PENALTY = -0.1
WALL_PENALTY = -2.0
CAR_COLLISION_PENALTY = -2.0
