
ROAD_PENALTY = 0.0
SAFE_ZONE_REWARD = 0.5
GAME_WON_REWARD = 10.0
ADVANCEMENT_REWARD = 2.5
GAME_OVER_PENALTY = -5.0
EXCEEDED_TIME_PENALTY = -2.0
STEP_PENALTY = -0.05
REGRESSION_PENALTY = -0.3
WALL_PENALTY = -3.0
CAR_COLLISION_PENALTY = -2.0
